// importing express as the comm protocal using api technology
const express = require('express');

// cross origin resource
const cors = require( 'cors' );

// express to make endpoints available
const app = express();
const PORT  = process.env.PORT || 5000;  // Default to 5000 if no PORT environment variable is set
// listens to an available port or default

app.use((req, res, next) => {
    res.setHeader('Content-Type', 'application/json');
    next();
  });  
//.....enabling middleware
app.use(cors());
app.use(express.json());

// routing the available data
const availableProblemsBasedOnTopics = {

    'mathematical-methods-for-physics-and-calculus': [
    { id: 1, subject: "Advanced Functions", question: "Show that the function f(x) = x⁵ - 5x³ + 4x is odd and determine its critical points.", difficulty: "intermediate", hint: "Check if f(-x) = -f(x) to prove it is odd. Use the first derivative to find the critical points and the second derivative to classify them." },
    { id: 2, subject: "Asymptotic Analysis", question: "Find the asymptotic behavior of the integral I(λ) = ∫₀^∞ e^(-λx²) dx as λ → ∞ using Laplace's method.", difficulty: "advanced", hint: "For large λ, the integral behaves like a Gaussian integral. Use Laplace’s method to approximate the integral for large λ." },
    { id: 3, subject: "Differential Calculus", question: "Find and classify all extrema of the function f(x, y) = x² + xy + y² using the Hessian matrix.", difficulty: "advanced", hint: "Compute the first and second partial derivatives. The Hessian matrix will help classify the critical points." },
    { id: 4, subject: "Integral Calculus", question: "Evaluate the integral ∫₀^∞ x³ / (e^x - 1) dx and relate it to the Riemann zeta function.", difficulty: "challenging", hint: "Use the series expansion of 1 / (e^x - 1) and recognize the connection to the Riemann zeta function." },
    { id: 5, subject: "Complex Analysis", question: "Evaluate the integral ∫_C (z² + 1)/(z - i) dz where C is the circle |z| = 2 using the Cauchy integral formula.", difficulty: "advanced", hint: "Apply the Cauchy Integral Formula for a function with a simple pole at z = i inside the contour." },
    { id: 6, subject: "Differential Calculus", question: "Using the method of Lagrange multipliers, find the maximum and minimum of f(x, y) = x² + y² subject to the constraint x + y = 1.", difficulty: "advanced", hint: "Set up the Lagrange multiplier equations: ∇f = λ ∇g, where g(x, y) = x + y - 1." },
    { id: 7, subject: "Differential Calculus", question: "Let f(x, y) = e^(xy). Find the directional derivative at (1, 0) in the direction of the vector (1, 1).", difficulty: "intermediate", hint: "Use the gradient of f(x, y) and compute the dot product with the given direction vector." },
    { id: 8, subject: "Integral Calculus", question: "Use Fubini’s theorem to evaluate ∬_D (x + y) dA, where D is the region bounded by x = 0, y = 0, and x + y = 1.", difficulty: "intermediate", hint: "Set up the integral with respect to x and y in the limits defined by the region D." },
    { id: 9, subject: "Integral Calculus", question: "Evaluate the improper integral ∫₀^∞ x⁴ e^(-x²) dx using the Gamma function.", difficulty: "advanced", hint: "Recognize the structure of the Gamma function, specifically for n = 5/2." },
    { id: 10, subject: "Integral Calculus", question: "Change the order of integration and evaluate the double integral ∫₀¹ ∫_x^1 (x/y) dy dx.", difficulty: "advanced", hint: "Rearrange the limits of integration and evaluate the integrals in the new order." },
    { id: 11, subject: "Integral Calculus", question: "Use Green’s theorem to evaluate the line integral ∮_C (y² dx + x² dy), where C is the boundary of the square with vertices (0,0), (1,0), (1,1), (0,1).", difficulty: "advanced", hint: "Convert the line integral into a double integral using Green’s theorem. Evaluate the resulting integral." },
    { id: 12, subject: "Integral Calculus", question: "Evaluate the triple integral ∭_E z dV, where E is the solid bounded by the cylinder x² + y² = 1 and the planes z = 0 and z = 1 - x² - y².", difficulty: "challenging", hint: "Set up the triple integral in cylindrical coordinates and evaluate the bounds accordingly." },
    { id: 13, subject: "Differential Equations", question: "Solve the differential equation dy/dx = x² - y² with initial condition y(0) = 0.", difficulty: "advanced", hint: "Try separating variables or using an appropriate substitution to solve the equation." },
    { id: 14, subject: "Series Expansion", question: "Find the Taylor series expansion of e^x around x = 0 up to the 4th order term.", difficulty: "intermediate", hint: "Recall the general form of the Taylor series for e^x and compute the first few derivatives of e^x at x = 0." },
    { id: 15, subject: "Multivariable Calculus", question: "Evaluate the surface integral ∮_S F · dS, where F = (x²y, yz², x²z) and S is the surface of the cube [0, 1] x [0, 1] x [0, 1].", difficulty: "advanced", hint: "Use the Divergence Theorem to convert the surface integral into a volume integral." },
    { id: 16, subject: "Integral Calculus", question: "Evaluate the integral ∫₀^∞ (1/x² + 1) e^(-x) dx.", difficulty: "challenging", hint: "Break the integral into two parts and use standard integral tables or techniques." },
    { id: 17, subject: "Differential Calculus", question: "Find the gradient of the scalar function f(x, y, z) = x² + y² + z² and evaluate it at the point (1, -1, 2).", difficulty: "intermediate", hint: "The gradient is the vector of partial derivatives of f with respect to x, y, and z." },
    { id: 18, subject: "Vector Calculus", question: "Compute the curl of the vector field F = (yz, xz, xy) at the point (1, 1, 1).", difficulty: "advanced", hint: "Use the formula for the curl of a vector field: ∇ × F = (∂/∂x, ∂/∂y, ∂/∂z) × F." }
]
,

   'linear-algebra': [
    { id: 1, subject: "Vector Spaces", question: "Prove that any two finite-dimensional vector spaces of the same dimension over the same field are isomorphic.", difficulty: "advanced", hint: "Consider a linear transformation between the two vector spaces and show that it is invertible." },
    { id: 2, subject: "Vector Spaces", question: "Given a set of vectors in ℝ⁵, determine whether they form a basis and compute the change-of-basis matrix to another orthonormal basis.", difficulty: "advanced", hint: "Check if the set of vectors is linearly independent and spans ℝ⁵. Use the Gram-Schmidt process to find an orthonormal basis and compute the change-of-basis matrix." },
    { id: 3, subject: "Eigenvalues and Eigenvectors", question: "Prove that a Hermitian matrix has real eigenvalues and orthogonal eigenvectors.", difficulty: "advanced", hint: "Use the fact that Hermitian matrices are equal to their conjugate transpose and apply the spectral theorem." },
    { id: 4, subject: "Eigenvalues and Eigenvectors", question: "Let A be a 4×4 matrix with one eigenvalue λ = 3 of algebraic multiplicity 4. Determine the possible Jordan canonical forms of A.", difficulty: "challenging", hint: "Consider the geometric multiplicity of the eigenvalue and use the Jordan form structure for the matrix." },
    { id: 5, subject: "Hilbert Spaces", question: "Let H be a Hilbert space and let {e_n} be an orthonormal sequence in H. Prove that the series ∑ ⟨x, e_n⟩ e_n converges in H to x iff {e_n} is a complete orthonormal system.", difficulty: "challenging", hint: "Use the Bessel inequality and show that the series converges to x if and only if {e_n} is complete." },
    { id: 6, subject: "Hilbert Spaces", question: "Demonstrate that every separable Hilbert space is isomorphic to ℓ².", difficulty: "challenging", hint: "Construct an isomorphism between a separable Hilbert space and ℓ² by using the orthonormal basis." },
    { id: 7, subject: "Systems of Equations", question: "Determine the conditions on parameters a and b such that the following system has a unique solution: AX = B, where A = [[1, a], [b, 1]] and B = [1, 0]^T.", difficulty: "intermediate", hint: "Check the determinant of matrix A. If it is non-zero, the system has a unique solution." },
    { id: 8, subject: "Systems of Equations", question: "Use LU decomposition to solve a 4×4 sparse matrix system and analyze its numerical stability.", difficulty: "challenging", hint: "Decompose the matrix into lower and upper triangular matrices and solve the system using forward and backward substitution. Analyze the condition number for numerical stability." },
    { id: 9, subject: "Advanced Solving Methods", question: "Implement the Conjugate Gradient Method to solve a symmetric positive-definite linear system. Discuss convergence criteria.", difficulty: "challenging", hint: "Use the residual and the search direction to iteratively solve the system. Convergence is guaranteed if the matrix is symmetric and positive-definite." },
    { id: 10, subject: "Advanced Solving Methods", question: "Compare the performance and accuracy of SVD vs. QR decomposition in solving overdetermined systems.", difficulty: "challenging", hint: "SVD provides a more stable numerical solution, while QR is more efficient for large systems. Compare both methods for a given overdetermined system." },
    { id: 11, subject: "Levi Civita", question: "Prove the identity ε_{ijk} ε_{klm} = δ_{il} δ_{jm} - δ_{im} δ_{jl} and explain its significance in tensor calculus.", difficulty: "challenging", hint: "Use the properties of the Levi-Civita symbol and perform summation over the repeated indices to verify the identity." },
    { id: 12, subject: "Orthogonalization", question: "Apply the Gram-Schmidt process to orthogonalize the set {(1,1,0), (1,0,1), (0,1,1)} in ℝ³.", difficulty: "advanced", hint: "Apply the Gram-Schmidt procedure step by step, subtracting the projections of each vector onto the previously orthogonalized vectors." },
    { id: 13, subject: "Vector Spaces", question: "Find the null space and column space of the matrix A = [[1, 2], [3, 4], [5, 6]].", difficulty: "intermediate", hint: "Use row reduction to find the null space and identify the linearly independent columns to determine the column space." },
    { id: 14, subject: "Linear Transformations", question: "Prove that the set of all linear transformations from ℝⁿ to ℝᵐ forms a vector space under pointwise addition and scalar multiplication.", difficulty: "intermediate", hint: "Verify that the axioms of a vector space hold for the set of linear transformations." },
    { id: 15, subject: "Eigenvalues and Eigenvectors", question: "Find the eigenvalues and eigenvectors of the matrix A = [[4, 1], [2, 3]].", difficulty: "intermediate", hint: "Solve the characteristic equation det(A - λI) = 0 and find the corresponding eigenvectors." },
    { id: 16, subject: "Orthogonal Matrices", question: "Prove that the inverse of an orthogonal matrix is also orthogonal.", difficulty: "advanced", hint: "Use the fact that for an orthogonal matrix Q, Q^T Q = I. This implies Q^(-1) = Q^T." },
    { id: 17, subject: "Determinants", question: "Show that the determinant of a triangular matrix is the product of its diagonal elements.", difficulty: "intermediate", hint: "Use the cofactor expansion along the first row (or column) to simplify the calculation of the determinant for a triangular matrix." },
    { id: 18, subject: "Vector Spaces", question: "Prove that the intersection of two subspaces is a subspace.", difficulty: "intermediate", hint: "Show that the intersection satisfies the axioms of a subspace: closure under addition and scalar multiplication." }
]
,

    'methods-in-mathematical-physics': [
    { id: 13, subject: "Complex Analysis", question: "Evaluate ∮_C (z² + 1)/(z² + 2z + 2) dz where C is the circle |z| = 3 using the Residue Theorem.", difficulty: "advanced", hint: "Find the poles of the integrand inside the contour and apply the Residue Theorem." },
    { id: 14, subject: "Complex Analysis", question: "Find all singularities and classify them for f(z) = sin(z)/z³.", difficulty: "intermediate", hint: "Examine the singularities of sin(z) at z = 0 and classify the singularity at z = 0." },
    { id: 15, subject: "Complex Analysis", question: "Use Cauchy's integral formula to compute ∮_C (e^z)/(z - i)² dz where C is the circle |z| = 2.", difficulty: "advanced", hint: "Use the fact that Cauchy’s formula for higher derivatives gives the result for integrals with powers of (z - a)." },
    { id: 16, subject: "Complex Series", question: "Determine the radius and region of convergence of the series ∑ (zⁿ)/(n² + 1).", difficulty: "intermediate", hint: "Apply the root test or ratio test to determine the radius of convergence." },
    { id: 17, subject: "Differential Equations", question: "Solve the Legendre differential equation (1 - x²)y'' - 2xy' + l(l+1)y = 0 for l = 2.", difficulty: "advanced", hint: "Use the standard form of the Legendre equation and find the solution in terms of associated Legendre polynomials." },
    { id: 18, subject: "Differential Equations", question: "Solve the Hermite differential equation y'' - 2xy' + 2ny = 0 for n = 3 and find the polynomial solution.", difficulty: "advanced", hint: "The solution to the Hermite equation for integer n is a polynomial, so look for a degree-3 polynomial solution." },
    { id: 19, subject: "Differential Equations", question: "Solve the Laguerre differential equation xy'' + (1 - x)y' + ny = 0 for n = 2.", difficulty: "advanced", hint: "The general solution to this equation is a Laguerre polynomial. Use the form for Lₙ(x) to solve it." },
    { id: 20, subject: "Fourier Analysis", question: "Find the Fourier series of f(x) = x² on the interval [-π, π].", difficulty: "advanced", hint: "Use the standard Fourier series formulas and compute the coefficients aₙ and bₙ." },
    { id: 21, subject: "Fourier Transform", question: "Compute the Fourier transform of f(x) = e^(-a|x|) where a > 0.", difficulty: "advanced", hint: "Split the integral into two parts, one for x > 0 and one for x < 0, and solve each part separately." },
    { id: 22, subject: "Laplace Transform", question: "Find the Laplace transform of f(t) = t e^(2t) sin(3t).", difficulty: "advanced", hint: "Use the standard Laplace transforms of e^(2t) and sin(3t), and apply the derivative property for t." },
    { id: 23, subject: "Taylor Series", question: "Find the Taylor series expansion of f(z) = ln(1 + z) around z = 0 and determine the radius of convergence.", difficulty: "intermediate", hint: "Use the known Taylor series expansion for ln(1+z) and check the convergence for |z| < 1." },
    { id: 24, subject: "Polynomials", question: "Show that the Legendre polynomials Pₙ(x) are orthogonal on [-1, 1] with respect to the weight function w(x) = 1.", difficulty: "advanced", hint: "Use the orthogonality condition ∫ Pₙ(x) Pₘ(x) dx = 0 for n ≠ m and use the standard recurrence relations for Pₙ(x)." },
    { id: 25, subject: "Polynomials", question: "Find the first four Laguerre polynomials using Rodrigues' formula.", difficulty: "advanced", hint: "Apply Rodrigues' formula to compute the first four polynomials and verify their orthogonality." },
    { id: 26, subject: "Laplace Transform", question: "Use Laplace transforms to solve the ODE: y'' + 4y = δ(t - π), y(0) = 0, y'(0) = 0.", difficulty: "challenging", hint: "Take the Laplace transform of both sides of the ODE and use the properties of the delta function." },
    { id: 27, subject: "Fourier Transform", question: "Use the Fourier transform to solve the heat equation ∂u/∂t = α² ∂²u/∂x² with u(x, 0) = e^{-x²}.", difficulty: "challenging", hint: "Take the Fourier transform of both sides of the equation and solve in the frequency domain." },
    { id: 28, subject: "Partial Differential Equations", question: "Solve the 1D wave equation with fixed ends: ∂²u/∂t² = c² ∂²u/∂x², u(0,t)=u(L,t)=0, u(x,0)=sin(πx/L), ∂u/∂t(x,0)=0.", difficulty: "advanced", hint: "Use separation of variables and solve for the eigenfunctions and eigenvalues of the spatial part." },
    { id: 29, subject: "Partial Differential Equations", question: "Use separation of variables to solve Laplace’s equation in a rectangular domain with Dirichlet boundary conditions.", difficulty: "advanced", hint: "Assume a solution of the form u(x, y) = X(x)Y(y) and solve the resulting ODEs for each variable." },
    { id: 30, subject: "Green's Functions", question: "Find the Green's function for the ODE: -d²y/dx² = f(x), with boundary conditions y(0)=y(1)=0.", difficulty: "challenging", hint: "Solve the equation for the Green's function by using the method of constructing piecewise solutions." },
    { id: 31, subject: "Green's Functions", question: "Use Green’s function to solve Poisson’s equation ∇²φ = -ρ(x) in one dimension with φ(0) = φ(L) = 0.", difficulty: "advanced", hint: "Find the Green's function for the given boundary conditions and then apply it to solve the Poisson equation." },
    { id: 32, subject: "Sturm–Liouville Theory", question: "Find the eigenfunctions and eigenvalues for y'' + λy = 0 on [0, π] with y(0)=0, y(π)=0 and show orthogonality.", difficulty: "challenging", hint: "Solve the equation and use the boundary conditions to find the eigenvalues. Prove orthogonality using the Sturm-Liouville theory." },
    { id: 33, subject: "Sturm–Liouville Theory", question: "Show that the Bessel functions J₀(αₙx) are eigenfunctions of a Sturm–Liouville problem on [0,1].", difficulty: "challenging", hint: "Derive the eigenvalues and eigenfunctions for the given problem and check the orthogonality of the Bessel functions." },
    { id: 34, subject: "Distribution Theory", question: "Prove that the derivative of the Heaviside function H(x) in the sense of distributions is the Dirac delta δ(x).", difficulty: "advanced", hint: "Use the definition of the distributional derivative and test the result on a test function." },
    { id: 35, subject: "Distribution Theory", question: "Evaluate the distributional limit of f_ε(x) = ε / (π(x² + ε²)) as ε → 0⁺.", difficulty: "challenging", hint: "Recognize that this is a regularization of the Dirac delta and use it to find the distributional limit." }
]
,
'vector-calculus': [
    { id: 36, subject: "Gradient", question: "Compute the gradient of f(x, y, z) = x²y + yz² and interpret it as a vector field.", difficulty: "intermediate", hint: "Recall that the gradient is the vector of partial derivatives of the function with respect to each coordinate." },
    { id: 37, subject: "Divergence", question: "Evaluate the divergence of the vector field F(x, y, z) = (xy, yz, zx) and determine points of zero divergence.", difficulty: "intermediate", hint: "Use the formula for divergence: ∇·F = ∂F₁/∂x + ∂F₂/∂y + ∂F₃/∂z." },
    { id: 38, subject: "Curl", question: "Compute the curl of F(x, y, z) = (yz, xz, xy) and determine whether the field is conservative.", difficulty: "advanced", hint: "Use the curl formula: ∇×F = ( ∂F₃/∂y - ∂F₂/∂z, ∂F₁/∂z - ∂F₃/∂x, ∂F₂/∂x - ∂F₁/∂y )." },
    { id: 39, subject: "Stokes' Theorem", question: "Use Stokes' theorem to evaluate ∮_C F·dr where F = (y, -x, z), and C is the boundary of the upper hemisphere x² + y² + z² = 1, z ≥ 0.", difficulty: "challenging", hint: "Stokes' theorem relates a line integral around a closed curve to a surface integral of the curl of the vector field over a surface bounded by the curve." },
    { id: 40, subject: "Gauss's Theorem", question: "Use Gauss’s divergence theorem to compute the outward flux of F = (x, y, z) through the surface of the unit sphere.", difficulty: "challenging", hint: "Apply Gauss's divergence theorem: ∮_S F·dA = ∫_V (∇·F) dV, where V is the volume enclosed by the surface S." },
    { id: 41, subject: "Flux", question: "Find the flux of the vector field F(x, y, z) = z i + y j + x k through the surface z = 1 - x² - y² (a paraboloid cap).", difficulty: "challenging", hint: "To calculate flux, use the surface integral: ∮_S F·dA, where dA is the area element on the surface." },
    { id: 42, subject: "Fields", question: "Verify if the field F(x, y, z) = (y², 2xy, z) is solenoidal and/or irrotational.", difficulty: "advanced", hint: "Check if the divergence (∇·F) and curl (∇×F) of the field are zero to determine if it is solenoidal and/or irrotational." },
    { id: 43, subject: "Sources and Sinks", question: "Show that the vector field F(x, y) = (x/r², y/r²), r = sqrt(x² + y²), has a source at the origin in the distributional sense.", difficulty: "challenging", hint: "Use the concept of distributional derivatives to compute the divergence and examine the behavior at the origin." },
    { id: 44, subject: "Volume-Surface Equivalence", question: "Using the divergence theorem, prove that the net flux of a constant vector field through any closed surface equals zero.", difficulty: "intermediate", hint: "Recall that the divergence of a constant vector field is zero, so the volume integral of the divergence will also be zero." },
    { id: 45, subject: "Incompressibility", question: "Prove that the velocity field of an incompressible fluid must satisfy ∇·v = 0.", difficulty: "advanced", hint: "The incompressibility condition is equivalent to the statement that the divergence of the velocity field must be zero." },
    { id: 46, subject: "Liouville's Theorem (Vector Calculus)", question: "Use Liouville’s theorem to show that a bounded, entire vector field with zero divergence and zero curl must be constant.", difficulty: "challenging", hint: "Liouville’s theorem states that any bounded entire vector field must be constant if it has zero divergence and curl." },
    { id: 47, subject: "Gradient", question: "Compute the gradient of f(x, y, z) = e^(x² + y² + z²) and interpret it as a vector field.", difficulty: "intermediate", hint: "Differentiate f(x, y, z) with respect to each coordinate to find the components of the gradient." },
    { id: 48, subject: "Divergence", question: "Evaluate the divergence of the vector field F(x, y, z) = (x²y, yz², zx²).", difficulty: "intermediate", hint: "Use the formula for divergence: ∇·F = ∂F₁/∂x + ∂F₂/∂y + ∂F₃/∂z." },
    { id: 49, subject: "Curl", question: "Compute the curl of F(x, y, z) = (y²z, x²z, x²y) and determine whether the field is conservative.", difficulty: "advanced", hint: "Use the curl formula and check if the result is zero, indicating a conservative field." },
    { id: 50, subject: "Stokes' Theorem", question: "Use Stokes' theorem to evaluate ∮_C F·dr where F = (x², y², z²), and C is the boundary of the region defined by x² + y² + z² ≤ 1.", difficulty: "challenging", hint: "Use Stokes' theorem and express the integral in terms of the surface integral of curl F." },
    { id: 51, subject: "Gauss's Theorem", question: "Use Gauss’s divergence theorem to compute the outward flux of F = (x², y², z²) through the surface of the unit sphere.", difficulty: "challenging", hint: "First, compute the divergence of F, then apply the divergence theorem to compute the flux through the sphere." },
    { id: 52, subject: "Flux", question: "Find the flux of the vector field F(x, y, z) = (z, y, x) through the surface z = 2 - x² - y² (a paraboloid cap).", difficulty: "challenging", hint: "Set up the surface integral for flux by finding the appropriate surface normal and then integrating over the surface." },
    { id: 53, subject: "Fields", question: "Verify if the field F(x, y, z) = (x², y², z²) is solenoidal and/or irrotational.", difficulty: "advanced", hint: "Check the divergence and curl of the field to determine if the field is solenoidal (divergence-free) and irrotational (curl-free)." },
    { id: 54, subject: "Sources and Sinks", question: "Show that the vector field F(x, y) = (x²/r², y²/r²), r = sqrt(x² + y²), has a source at the origin in the distributional sense.", difficulty: "challenging", hint: "Use the distributional derivative of the vector field to examine the behavior at the origin and find the source." },
    { id: 55, subject: "Incompressibility", question: "Prove that the velocity field of an incompressible fluid must satisfy ∇·v = 0 for a three-dimensional incompressible fluid.", difficulty: "advanced", hint: "This condition follows from the fact that the volume of fluid does not change over time, and the velocity field must be divergence-free." }
  ]
  ,
 'newtonian-mechanics': [
    { id: 1, subject: "Kinematics", question: "A projectile is launched from ground level with speed v at an angle θ. Derive the time of flight, range, and maximum height.", difficulty: "intermediate", hint: "Use the kinematic equations of motion for projectile motion, considering the horizontal and vertical components of velocity." },
    { id: 2, subject: "Relative Motion", question: "Two trains move on parallel tracks with speeds v₁ and v₂. Derive the expression for the relative velocity and find the time until they are abreast given an initial separation.", difficulty: "intermediate", hint: "The relative velocity can be found by vector subtraction of the two velocities. Consider the initial separation distance." },
    { id: 3, subject: "Newton’s Second Law", question: "A block of mass m is pushed against a frictionless vertical wall with force F. What is the minimum value of F to prevent the block from falling if the coefficient of static friction is μ?", difficulty: "advanced", hint: "Balance the forces in the vertical direction, considering the static frictional force preventing the block from sliding." },
    { id: 4, subject: "Mass Distribution", question: "Find the center of mass of a uniform semicircular plate of radius R.", difficulty: "advanced", hint: "Use the symmetry of the semicircle and integrate over the area to find the center of mass." },
    { id: 5, subject: "Moment of Inertia", question: "Calculate the moment of inertia of a uniform solid sphere of mass M and radius R about an axis through its center.", difficulty: "intermediate", hint: "Use the standard formula for the moment of inertia of a solid sphere: I = (2/5)MR²." },
    { id: 6, subject: "Parallel Axis Theorem", question: "Use the parallel axis theorem to compute the moment of inertia of a uniform rod of length L and mass M about an axis perpendicular to the rod and passing through one of its ends.", difficulty: "intermediate", hint: "The moment of inertia about an axis passing through one end is the moment of inertia about the center of mass plus the mass times the distance squared." },
    { id: 7, subject: "Rotational Dynamics", question: "A disk of radius R and mass M is rolling without slipping. Derive the total kinetic energy and find the acceleration of its center of mass when a force F is applied.", difficulty: "advanced", hint: "Consider both rotational and translational kinetic energy. The no-slip condition gives a relation between the linear and angular velocities." },
    { id: 8, subject: "Torque and Angular Momentum", question: "A particle of mass m is moving in a circle of radius r with constant angular speed ω. Derive its angular momentum and show how torque relates to the rate of change of angular momentum.", difficulty: "advanced", hint: "Angular momentum L = mvr, where v = ωr. Torque τ is the rate of change of angular momentum." },
    { id: 9, subject: "Work-Energy Theorem", question: "A spring with spring constant k is compressed a distance x. Use the work-energy theorem to find the speed of a mass m released from the spring on a frictionless surface.", difficulty: "intermediate", hint: "The work done by the spring is stored as potential energy. Use the work-energy theorem to equate potential energy to kinetic energy." },
    { id: 10, subject: "Conservation of Momentum", question: "Two blocks of masses m₁ and m₂ collide elastically on a frictionless surface. Derive expressions for their final velocities in terms of m₁, m₂, and initial velocities.", difficulty: "challenging", hint: "Use both conservation of momentum and conservation of kinetic energy for elastic collisions." },
    { id: 11, subject: "Central Forces", question: "A planet moves in an elliptical orbit around the sun under the influence of gravity. Derive Kepler’s second law using angular momentum conservation.", difficulty: "challenging", hint: "Use conservation of angular momentum to show that the rate of area swept out by the radius vector is constant." },
    { id: 12, subject: "Oscillations", question: "A mass-spring system exhibits simple harmonic motion. Derive the equation of motion and find the expression for the period in terms of mass and spring constant.", difficulty: "intermediate", hint: "Use Hooke's law and Newton's second law to derive the equation of motion. The period is related to the mass and spring constant." },
    { id: 13, subject: "Damped Motion", question: "A damped harmonic oscillator satisfies the equation mẍ + bẋ + kx = 0. Classify the motion based on the damping ratio and derive the general solution in each regime.", difficulty: "challenging", hint: "Analyze the solution for underdamped, critically damped, and overdamped cases. The damping ratio determines the behavior of the system." },
    { id: 14, subject: "Equilibrium", question: "A uniform beam of length L is suspended horizontally by two supports at its ends. A mass m is placed at a distance x from the left support. Find the forces on the supports.", difficulty: "advanced", hint: "Use the conditions of static equilibrium: the sum of forces and the sum of torques must both equal zero." },
    { id: 15, subject: "Non-Inertial Frames", question: "A pendulum is hung in an accelerating elevator. Derive the effective gravity and find the change in its period of oscillation.", difficulty: "challenging", hint: "The effective acceleration due to gravity is modified by the acceleration of the elevator. Use the modified acceleration to find the period." },
    { id: 16, subject: "Circular Motion", question: "A car is moving around a curve of radius R at speed v. Derive the minimum coefficient of friction required to keep the car from slipping.", difficulty: "intermediate", hint: "Use the centripetal force equation and set the frictional force equal to the required centripetal force." },
    { id: 17, subject: "Elastic Collisions", question: "A ball of mass m₁ collides elastically with a stationary ball of mass m₂. Derive the velocities of both balls after the collision in terms of their initial velocities.", difficulty: "advanced", hint: "Use conservation of momentum and kinetic energy to solve for the velocities of both balls after the collision." },
    { id: 18, subject: "Gravitational Potential Energy", question: "A satellite is in orbit around the Earth at a distance r from the center of the Earth. Derive the total mechanical energy of the satellite in orbit.", difficulty: "intermediate", hint: "The total mechanical energy is the sum of the kinetic and potential energy. Use the gravitational potential energy and the orbital speed." },
    { id: 19, subject: "Frictional Forces", question: "A block is moving with constant velocity on a rough surface. Determine the coefficient of kinetic friction.", difficulty: "intermediate", hint: "Use Newton's second law to equate the applied force to the frictional force, and solve for the coefficient of friction." },
    { id: 20, subject: "Work and Energy", question: "A force F(x) = kx is applied to a spring. Calculate the work done to stretch the spring from x₁ to x₂.", difficulty: "intermediate", hint: "The work done is the integral of force over displacement. Use the formula for the force applied to the spring to find the work done." }
  ]
  ,
  'analytical-mechanics': [
  { id: 1, subject: "Generalized Coordinates", question: "Double pendulum: pick coordinates, derive T & V.", difficulty: "intermediate", hint: "Use angular coordinates for each pendulum and consider their kinetic and potential energy separately." },
  { id: 2, subject: "Generalized Speeds & Accelerations", question: "Particle on cylinder: use cylindrical coords, find velocities, accelerations, constraints.", difficulty: "intermediate", hint: "Express radial motion constraint and use θ and z as generalized coordinates." },
  { id: 3, subject: "Lagrangian Formalism", question: "Charged particle in B-field: derive Lagrangian, Euler-Lagrange eqs, cyclic coords.", difficulty: "advanced", hint: "Use vector potential \( \vec{A} \) such that \( \vec{B} = \nabla \times \vec{A} \)." },
  { id: 4, subject: "Constrained Systems", question: "Bead on curve: apply Lagrange multipliers for motion eqs.", difficulty: "challenging", hint: "Impose the constraint equation directly in the Lagrangian via a multiplier." },
  { id: 5, subject: "Generalized Momenta", question: "Central potential: derive angular momentum, discuss conserved quantities.", difficulty: "intermediate", hint: "Use polar or spherical coordinates and identify cyclic variables." },
  { id: 6, subject: "Hamiltonian Formalism", question: "1D SHO: derive Hamiltonian, get Hamilton's eqs, solve.", difficulty: "intermediate", hint: "Start from the Lagrangian \( L = T - V \) and perform a Legendre transform." },
  { id: 7, subject: "Canonical Transformations", question: "Show Q = ln(q), P = qp is canonical; use generating function.", difficulty: "advanced", hint: "Try using a type-2 generating function \( F_2(q, P) \)." },
  { id: 8, subject: "Phase Space", question: "Plot phase space of SHO & pendulum; compare topology.", difficulty: "intermediate", hint: "Note bounded vs unbounded motion and periodicity in trajectories." },
  { id: 9, subject: "Liouville’s Theorem", question: "1D non-interacting system: prove phase space density constancy.", difficulty: "challenging", hint: "Use the continuity equation in phase space and Hamilton's equations." },
  { id: 10, subject: "Noether’s Theorem", question: "Prove theorem; apply to rotations → angular momentum conservation.", difficulty: "challenging", hint: "Identify the symmetry transformation and write the corresponding conserved quantity." },
  { id: 11, subject: "Advanced Systems", question: "Relativistic free particle: get proper-time Lagrangian & motion eqs.", difficulty: "challenging", hint: "Use the invariant interval \( ds \) and parameterize by proper time τ." },
  { id: 12, subject: "Von Neumann Formalism", question: "Define von Neumann bracket, relate to Poisson in classical limit.", difficulty: "advanced", hint: "Recall \( \{f, g\}_{\text{vN}} = \frac{1}{i\hbar}[f, g] \) and take the limit \( \hbar \to 0 \)." },
  { id: 13, subject: "Hamilton-Jacobi Theory", question: "Solve H-J eq for SHO, get action and motion.", difficulty: "advanced", hint: "Use separation of variables on the H-J equation and compare to classical solutions." },
  { id: 14, subject: "Equivalence of Formalisms", question: "Show Lagrangian ↔ Hamiltonian equivalence for potential systems.", difficulty: "intermediate", hint: "Use the Legendre transform and compare the equations of motion from both sides." },
  { id: 15, subject: "Field Theory & Phase Space", question: "Scalar field φ(x,t): derive Hamiltonian density, apply Liouville in field space.", difficulty: "challenging", hint: "Use \( \pi = \partial \mathcal{L}/\partial \dot{\phi} \) and express the Hamiltonian density in terms of \( \phi \) and \( \pi \)." }
]

,'oscillations-and-waves': [
  { id: 1, subject: "Simple Harmonic Motion", question: "A particle of mass m attached to a spring with stiffness k undergoes SHM. Derive the equation of motion and find expressions for period, total energy, and phase.", difficulty: "intermediate", hint: "Use Newton’s second law and Hooke’s law to derive the differential equation." },
  { id: 2, subject: "Damped Oscillations", question: "A mass-spring system with damping constant b satisfies mẍ + bẋ + kx = 0. Classify the motion based on the damping ratio and sketch typical responses.", difficulty: "intermediate", hint: "Define the damping ratio \( \zeta = \frac{b}{2\sqrt{mk}} \) and consider underdamped, critically damped, and overdamped cases." },
  { id: 3, subject: "Forced Oscillations", question: "A damped oscillator is driven by an external sinusoidal force F₀cos(ωt). Derive the steady-state solution and find the amplitude and phase as a function of driving frequency.", difficulty: "advanced", hint: "Use the method of particular solutions and assume a trial solution of the form \( x(t) = A \cos(\omega t - \delta) \)." },
  { id: 4, subject: "Resonance Phenomena", question: "Show that the amplitude of a driven, damped oscillator reaches a maximum at a particular frequency. Derive the condition for resonance and discuss the effect of damping.", difficulty: "intermediate", hint: "Find the frequency at which the amplitude expression is maximized; analyze the denominator." },
  { id: 5, subject: "Beats Phenomenon", question: "Two harmonic oscillations of slightly different frequencies are added. Derive the expression for the resultant motion and show how beats arise.", difficulty: "intermediate", hint: "Use the trigonometric identity for the sum of cosines to identify the envelope function." },
  { id: 6, subject: "Coupled Oscillators", question: "Two identical masses are connected by three springs (wall–mass–mass–wall system). Set up the equations of motion and find the normal modes and their frequencies.", difficulty: "challenging", hint: "Assume displacements of the form \( x_i(t) = A_i \cos(\omega t) \) and solve the resulting eigenvalue problem." },
  { id: 7, subject: "Interference", question: "Derive the condition for constructive and destructive interference for two coherent sources emitting sinusoidal waves of the same frequency.", difficulty: "intermediate", hint: "Consider the path difference between the waves and relate it to the wavelength." },
  { id: 8, subject: "Wave Superposition", question: "Two waves traveling in the same direction are given by y₁ = A cos(kx - ωt), y₂ = A cos(kx - ωt + φ). Derive the resultant wave and determine how the phase difference affects the amplitude.", difficulty: "intermediate", hint: "Use the cosine addition formula to combine the two waves into one." },
  { id: 9, subject: "Standing Waves", question: "A string fixed at both ends supports standing waves. Derive the expression for the allowed frequencies and describe the nodes and antinodes.", difficulty: "intermediate", hint: "Use boundary conditions at the fixed ends to find quantized wave numbers." },
  { id: 10, subject: "Coupled Pendulums", question: "Two pendulums of equal length are connected by a weak spring. Find the normal modes and show energy exchange between the modes over time.", difficulty: "challenging", hint: "Write the equations using small-angle approximation and look for symmetric and antisymmetric solutions." },
  { id: 11, subject: "Perturbation in Waves", question: "Consider a slightly inhomogeneous medium with small variations in wave speed. Use perturbation theory to show how the wave equation is modified and solve for first-order corrections to the wave function.", difficulty: "challenging", hint: "Expand the wave speed and wave function in terms of a small parameter and linearize." },
  { id: 12, subject: "Quality Factor", question: "Define the quality factor Q for a damped oscillator. Derive its expression in terms of system parameters and relate it to energy loss per cycle.", difficulty: "intermediate", hint: "Use \( Q = \frac{\omega_0}{2\beta} \) and express energy loss using the damping term." },
  { id: 13, subject: "Energy in Oscillations", question: "Calculate the time-averaged potential and kinetic energy of a harmonic oscillator. Show that the total energy remains constant in the absence of damping.", difficulty: "intermediate", hint: "Use \( x(t) = A \cos(\omega t + \phi) \) and compute averages over one period." },
  { id: 14, subject: "Wave Packets and Dispersion", question: "Construct a wave packet using a Gaussian distribution in k-space. Show how group velocity and dispersion arise in the evolution of the packet.", difficulty: "advanced", hint: "Fourier transform the wave packet and examine how the phase and group velocities differ." },
  { id: 15, subject: "Driven Coupled Oscillators", question: "One of two coupled masses is subjected to a periodic driving force. Derive the steady-state response and analyze energy transfer between the oscillators.", difficulty: "challenging", hint: "Use matrix methods or normal coordinates to decouple the equations and solve for forced motion." }
]
,
  'electrostatics': [
  { id: 1, subject: "Coulomb's Law", question: "Two point charges q₁ and q₂ are placed a distance r apart in vacuum. Derive the expression for the electric force between them and discuss vector direction.", difficulty: "introductory", hint: "Start with Coulomb's Law: F = k * |q₁q₂| / r². Use vector notation for direction." },
  { id: 2, subject: "Electric Field of a Point Charge", question: "Derive the electric field due to a point charge q at a distance r and sketch the field lines. Show the inverse-square behavior explicitly.", difficulty: "introductory", hint: "Use E = F/q₀ and apply Coulomb’s Law for the force." },
  { id: 3, subject: "Electric Field of a Continuous Charge Distribution", question: "Calculate the electric field at a point on the axis of a uniformly charged ring of radius R and total charge Q.", difficulty: "intermediate", hint: "Use symmetry and integrate the contributions of infinitesimal charge elements around the ring." },
  { id: 4, subject: "Gauss's Law - Spherical Symmetry", question: "Use Gauss’s Law to find the electric field due to a uniformly charged solid sphere both inside and outside the distribution.", difficulty: "intermediate", hint: "Use a spherical Gaussian surface. Apply the appropriate charge enclosed for r < R and r ≥ R." },
  { id: 5, subject: "Gauss's Law - Cylindrical Symmetry", question: "Apply Gauss’s Law to determine the electric field due to an infinitely long, uniformly charged cylinder. Discuss the field inside and outside.", difficulty: "intermediate", hint: "Use a cylindrical Gaussian surface co-axial with the charge distribution." },
  { id: 6, subject: "Electric Flux", question: "A point charge q is placed at the center of a cube. Calculate the total electric flux through one face of the cube using symmetry.", difficulty: "intermediate", hint: "Total flux through the cube is q/ε₀. Divide evenly among the six faces." },
  { id: 7, subject: "Electric Potential of a Point Charge", question: "Derive the electric potential at a distance r from a point charge and relate it to the work done in moving a test charge.", difficulty: "introductory", hint: "Use V = -∫E·dr from ∞ to r. Substitute E from the point charge formula." },
  { id: 8, subject: "Potential Due to a Continuous Distribution", question: "Find the electric potential on the axis of a uniformly charged rod of length L and linear charge density λ.", difficulty: "advanced", hint: "Integrate dV = (1/4πε₀)(dq / r) along the length of the rod." },
  { id: 9, subject: "Equipotential Surfaces", question: "Sketch and describe equipotential surfaces around a single point charge and between two like charges. Explain their relationship to field lines.", difficulty: "intermediate", hint: "Remember: equipotentials are always perpendicular to electric field lines." },
  { id: 10, subject: "Work and Electric Potential Energy", question: "Calculate the work done to bring two point charges q₁ and q₂ from infinity to a separation r. Relate it to electric potential energy.", difficulty: "intermediate", hint: "Use the definition of potential energy: U = k*q₁*q₂/r." },
  { id: 11, subject: "Dipole Electric Field", question: "Derive the electric field of an ideal electric dipole on the axial and equatorial lines in the far-field approximation.", difficulty: "advanced", hint: "Use superposition of fields from +q and -q, and expand in terms of 1/r³." },
  { id: 12, subject: "Field of a Plane of Charge", question: "Use Gauss’s Law to derive the electric field near an infinite sheet of uniform charge density σ.", difficulty: "intermediate", hint: "Use a Gaussian 'pillbox' intersecting the sheet. Field is constant near the sheet." },
  { id: 13, subject: "Electric Field from Volume Charge", question: "Find the electric field inside and outside a uniformly charged sphere with volume charge density ρ using Gauss’s Law.", difficulty: "intermediate", hint: "For r < R, use enclosed charge as a function of r³. For r > R, total charge is constant." },
  { id: 14, subject: "Electric Force on a Charge Distribution", question: "A line of charge of length L has uniform charge density λ. Compute the net force on a point charge q placed along the axis of the line.", difficulty: "challenging", hint: "Set up an integral using Coulomb’s Law and consider direction of each infinitesimal force." },
  { id: 15, subject: "Superposition Principle", question: "Two point charges are placed on the x-axis. Derive the expression for the net electric field at a general point along the axis and discuss equilibrium points.", difficulty: "intermediate", hint: "Sum the vector contributions from each charge and solve for E = 0 to find equilibrium." },
  { id: 16, subject: "Electric Field of a Dipole in General Position", question: "Find the electric field of a dipole at an arbitrary point in space using spherical coordinates.", difficulty: "advanced", hint: "Use potential V from dipole and then compute E = -∇V in spherical coordinates." },
  { id: 17, subject: "Potential Energy of a Dipole in an External Field", question: "A dipole of moment p is placed in a uniform electric field E. Derive the potential energy and discuss stable and unstable equilibrium positions.", difficulty: "intermediate", hint: "Use U = -p·E. Consider angles between dipole and field direction." },
  { id: 18, subject: "Field Line Patterns", question: "Sketch field lines for (a) a single charge, (b) two opposite charges, and (c) two like charges. Explain their qualitative features.", difficulty: "introductory", hint: "Remember that field lines begin on positive charges and end on negative ones, and they never cross." }
]

    , 
   'magnetostatics': [
  { id: 1, subject: "Biot–Savart Law", question: "Use the Biot–Savart law to derive the magnetic field at the center of a circular current loop of radius R carrying current I.", difficulty: "intermediate", hint: "Symmetry simplifies the integral—evaluate B from each segment and integrate over the loop." },
  { id: 2, subject: "Magnetic Field of a Straight Wire", question: "Using the Biot–Savart law, calculate the magnetic field at a distance r from an infinitely long, straight wire carrying a steady current I.", difficulty: "intermediate", hint: "Set up the integral using cylindrical symmetry and evaluate using standard trigonometric limits." },
  { id: 3, subject: "Ampère's Law - Infinite Wire", question: "Apply Ampère’s Law to derive the magnetic field around an infinitely long straight conductor carrying current I.", difficulty: "introductory", hint: "Use a circular Amperian loop concentric with the wire and apply the integral form of Ampère’s Law." },
  { id: 4, subject: "Ampère's Law - Solenoid", question: "Use Ampère’s Law to derive the magnetic field inside an ideal long solenoid with n turns per unit length carrying current I.", difficulty: "intermediate", hint: "Choose a rectangular Amperian loop that encloses several turns and apply symmetry assumptions." },
  { id: 5, subject: "Ampère's Law - Toroid", question: "Apply Ampère’s Law to compute the magnetic field inside a toroid of N turns carrying current I. Discuss the field outside the toroid.", difficulty: "intermediate", hint: "Use a circular Amperian path within the toroid. The field outside should cancel by symmetry." },
  { id: 6, subject: "Field Due to a Current Loop - Axis", question: "Calculate the magnetic field along the axis of a circular loop carrying current I using Biot–Savart law.", difficulty: "advanced", hint: "Only axial components survive—integrate carefully around the loop considering vertical symmetry." },
  { id: 7, subject: "Magnetic Vector Potential", question: "Derive the expression for the magnetic vector potential \( \\vec{A} \) for a long straight wire carrying current I. Discuss gauge freedom briefly.", difficulty: "advanced", hint: "Start from the Biot–Savart expression for \\( \\vec{A} \\), then integrate along the wire." },
  { id: 8, subject: "Differential Form of Ampère’s Law", question: "Derive the differential form of Ampère’s Law from its integral form and relate it to current density.", difficulty: "challenging", hint: "Apply Stokes’ Theorem to relate the line integral to the curl of B and express current as J." },
  { id: 9, subject: "Field from a Surface Current", question: "A sheet of current lies in the xy-plane with surface current density K in the x-direction. Use Ampère’s Law to find the magnetic field above and below the sheet.", difficulty: "advanced", hint: "Use a rectangular Amperian loop straddling the sheet. Consider symmetry above and below." },
  { id: 10, subject: "Magnetic Dipole Moment", question: "Define the magnetic dipole moment of a current loop and derive the magnetic field of a dipole in the far-field approximation.", difficulty: "intermediate", hint: "Use \\( \\vec{m} = I \\vec{A} \\) and expand the Biot–Savart law in the far-field limit." },
  { id: 11, subject: "Force Between Parallel Wires", question: "Two long parallel wires separated by a distance d carry currents I₁ and I₂. Derive the expression for the magnetic force per unit length on each wire.", difficulty: "introductory", hint: "Use B from one wire and apply Lorentz force per unit length on the second wire." },
  { id: 12, subject: "Magnetic Field from Volume Current", question: "A cylindrical wire of radius R carries a uniform volume current density J. Use Ampère’s Law to find the magnetic field inside and outside the wire.", difficulty: "intermediate", hint: "Use cylindrical Amperian loops for r < R and r > R and relate current enclosed to r²." },
  { id: 13, subject: "Differential Geometry - Curved Current Path", question: "Use the Biot–Savart law to qualitatively explain how curvature of a wire carrying current I affects the local direction and magnitude of the magnetic field.", difficulty: "advanced", hint: "Local curvature changes the angle and direction of \\( d\\vec{l} \\times \\hat{r} \\), affecting the resulting B." },
  { id: 14, subject: "Field Lines of Magnetic Field", question: "Sketch and describe the magnetic field lines around a circular current loop and compare them with those of a bar magnet.", difficulty: "introductory", hint: "Loop field lines resemble dipole patterns—closed loops emerge and return into the loop." },
  { id: 15, subject: "Energy Stored in Magnetic Field", question: "Derive the energy stored in the magnetic field of a solenoid and express it in terms of field strength and volume.", difficulty: "challenging", hint: "Use the relation \\( U = \\frac{1}{2\\mu_0} \\int B^2 \\, dV \\) for a uniform field inside the solenoid." }
]
,
 'extended-electro-magnetism': [
  { id: 1, subject: "Gauss’s Law for Electricity (Integral to Differential Form)", question: "Starting from the integral form of Gauss’s law, derive its differential form using the divergence theorem. Interpret the physical meaning of the result.", difficulty: "intermediate", hint: "Apply the divergence theorem to the electric flux integral over a closed surface." },
  { id: 2, subject: "Gauss’s Law for Magnetism", question: "Using the integral form of Gauss’s law for magnetism, show that the magnetic field has zero divergence and explain the physical meaning of this result.", difficulty: "introductory", hint: "Think about the absence of magnetic monopoles." },
  { id: 3, subject: "Faraday’s Law – Induction in a Loop", question: "A magnetic field through a circular loop changes with time. Use Faraday’s law in integral form to calculate the induced emf and derive the differential form.", difficulty: "intermediate", hint: "Use Stokes’ theorem and consider the time derivative of the magnetic flux." },
  { id: 4, subject: "Ampère–Maxwell Law – Charging Capacitor", question: "Analyze the magnetic field in the gap of a parallel plate capacitor being charged by a current I(t). Show how Maxwell’s displacement current completes Ampère’s law.", difficulty: "intermediate", hint: "No conduction current in the gap—think about how the electric field changes in time." },
  { id: 5, subject: "Displacement Current Density", question: "Define displacement current density and compute it for a parallel-plate capacitor with a time-varying voltage.", difficulty: "intermediate", hint: "Use the relation involving the time derivative of the electric displacement field." },
  { id: 6, subject: "Boundary Conditions at Interface", question: "Derive the boundary conditions for electric and magnetic fields at the interface between two media using Maxwell’s equations.", difficulty: "advanced", hint: "Apply the integral form of Maxwell’s equations to infinitesimal pillboxes and loops at the boundary." },
  { id: 7, subject: "Electromagnetic Wave Equation in Vacuum", question: "Starting from Maxwell’s equations in differential form, derive the wave equation for electric and magnetic fields in free space.", difficulty: "challenging", hint: "Take the curl of Faraday's law and use vector identities and Maxwell’s equations." },
  { id: 8, subject: "Electromagnetic Waves – Plane Wave Solution", question: "Verify that a plane wave solution satisfies Maxwell’s equations in free space and derive the relationship between E and B fields.", difficulty: "challenging", hint: "Assume sinusoidal E and B perpendicular to each other and the direction of propagation." },
  { id: 9, subject: "Poynting Vector and Energy Flow", question: "Define the Poynting vector and derive the expression for energy flux in an electromagnetic wave propagating through vacuum.", difficulty: "intermediate", hint: "Use the vector product of E and B and consider the units of power per area." },
  { id: 10, subject: "Integral Form of Faraday’s Law – Rotating Loop", question: "A rectangular loop rotates in a uniform magnetic field. Use Faraday’s law in integral form to calculate the induced emf.", difficulty: "intermediate", hint: "Express the magnetic flux as a function of the angle and differentiate with respect to time." },
  { id: 11, subject: "Gauss's Law – Non-uniform Charge Density", question: "Given a spatially varying charge density \( \rho(\vec{r}) \), use the differential form of Gauss’s law to find the divergence of the electric field.", difficulty: "intermediate", hint: "Directly apply the differential form: \( \nabla \cdot \vec{E} = \rho / \varepsilon_0 \)." },
  { id: 12, subject: "Integral vs Differential Form Comparison", question: "Compare and contrast the integral and differential forms of Maxwell’s equations. Give a physical example where each form is more useful.", difficulty: "introductory", hint: "Consider symmetry for integral form and local behavior for differential form." },
  { id: 13, subject: "Maxwell’s Equations in Material Media", question: "State Maxwell’s equations in a linear, isotropic, homogeneous dielectric and explain the role of the constitutive relations.", difficulty: "intermediate", hint: "Include \( \vec{D} = \varepsilon \vec{E} \), \( \vec{B} = \mu \vec{H} \) in your derivation." },
  { id: 14, subject: "Continuity Equation and Maxwell’s Equations", question: "Starting from the modified Ampère–Maxwell law, derive the continuity equation and interpret its meaning in terms of charge conservation.", difficulty: "challenging", hint: "Take the divergence of both sides of the modified Ampère's law." },
  { id: 15, subject: "Maxwell’s Equations in Covariant Form", question: "Outline the formulation of Maxwell’s equations using tensor notation in special relativity. Identify the electromagnetic field tensor.", difficulty: "advanced", hint: "Use the antisymmetric field tensor \( F^{\mu\nu} \) and four-current \( J^\mu \)." },
  { id: 16, subject: "Time-Harmonic Fields", question: "Assume sinusoidal time dependence and derive Maxwell's equations in phasor form. Explain their relevance in AC circuit theory and waveguides.", difficulty: "advanced", hint: "Replace time derivatives with multiplication by \( j\omega \)." },
  { id: 17, subject: "Wave Propagation in Dielectrics", question: "Derive the wave equation in a dielectric medium with permittivity \( \varepsilon \) and permeability \( \mu \). Discuss wave speed and impedance.", difficulty: "intermediate", hint: "Follow a similar process as in vacuum, but with \( \varepsilon \) and \( \mu \) instead of vacuum values." },
  { id: 18, subject: "Skin Effect and Conductors", question: "Explain the concept of skin depth in good conductors for high-frequency fields. Derive the exponential decay of fields inside the conductor.", difficulty: "advanced", hint: "Assume \( \vec{E} \propto e^{-\alpha z} \) and solve using Ohm’s law in Maxwell’s equations." },
  { id: 19, subject: "Radiation from an Oscillating Dipole", question: "Describe the far-field radiation from an oscillating electric dipole. Derive the angular distribution of radiated power.", difficulty: "challenging", hint: "Use the vector potential in the radiation zone approximation." },
  { id: 20, subject: "Energy Density in Electromagnetic Fields", question: "Derive expressions for the energy density stored in electric and magnetic fields. Discuss energy transfer in electromagnetic waves.", difficulty: "intermediate", hint: "Recall that energy density is proportional to the square of the field magnitudes." }
]
,
 "electrodynamics-and-relativity": [
    { id: 1, subject: "Electromagnetic Field of a Uniformly Moving Charge", question: "A point charge moves at constant velocity \( \\vec{v} \) close to the speed of light. Using special relativity and Maxwell’s equations, determine the electric and magnetic fields in the lab frame. Describe the field lines and angular compression effects.", difficulty: "challenging", hint: "Consider the relativistic transformations of the electric and magnetic fields and the effects of Lorentz contraction." },
    { id: 2, subject: "Lorentz Transformation of Electromagnetic Waves", question: "A plane electromagnetic wave travels in the \( \\hat{z} \) direction in one inertial frame. Use Lorentz transformations to determine the observed frequency, wavelength, and field directions in another frame moving with velocity \( v \\hat{z} \).", difficulty: "challenging", hint: "Remember that Lorentz transformations affect both the electric and magnetic field components as well as the wave's frequency and wavelength." },
    { id: 3, subject: "Relativistic Doppler Effect for EM Waves", question: "Derive the expression for the relativistic Doppler effect for electromagnetic waves. Explain the cases of source and observer moving toward and away from each other, and compare to the classical limit.", difficulty: "intermediate", hint: "Use the relativistic velocity addition formula and the invariant nature of the speed of light to derive the frequency shift." },
    { id: 4, subject: "Aberration of Light and Electromagnetic Field Direction", question: "Show how the direction of an incoming electromagnetic wave appears shifted due to relativistic motion (aberration of light). Derive the transformation of wave vector components between frames.", difficulty: "challenging", hint: "Use the velocity-addition formula and Lorentz transformations to derive the relationship between the wave vector in different frames." },
    { id: 5, subject: "Relativistic Beaming of Radiation", question: "Consider an accelerated charge emitting electromagnetic radiation. Explain the concept of relativistic beaming and derive the angular distribution of radiation in the ultra-relativistic limit.", difficulty: "challenging", hint: "Look into how the energy distribution changes due to relativistic effects and how the beaming phenomenon leads to a narrowing of the angular distribution." },
    { id: 6, subject: "Relativistic Invariance of Maxwell’s Equations", question: "Demonstrate that Maxwell’s equations retain their form under Lorentz transformations. Use the covariant tensor formulation to show the invariance explicitly.", difficulty: "advanced", hint: "Apply the four-dimensional field tensor and the concept of Lorentz invariance to show that Maxwell's equations are covariant." },
    { id: 7, subject: "Liénard–Wiechert Potentials and Retarded Fields", question: "Using the Liénard–Wiechert potentials, derive the expressions for the electric and magnetic fields of a point charge moving arbitrarily in special relativity. Identify near-field and radiation-field components.", difficulty: "advanced", hint: "Focus on the retarded time and the relationship between the source’s motion and the electromagnetic fields it generates." },
    { id: 8, subject: "Synchrotron Radiation from Relativistic Electrons", question: "Describe the radiation pattern and spectrum of synchrotron radiation emitted by relativistic electrons moving in a magnetic field. Highlight the role of relativistic effects.", difficulty: "challenging", hint: "Consider the motion of electrons in a magnetic field and how relativistic speeds influence the emitted radiation's frequency and angular distribution." },
    { id: 9, subject: "Radiation Reaction and Relativistic Motion", question: "Discuss the radiation reaction force experienced by an accelerating relativistic charge. Introduce the Lorentz-Abraham-Dirac equation and discuss its physical implications.", difficulty: "advanced", hint: "Explore the concept of self-interaction due to the electromagnetic field generated by the charge itself, and how the equation accounts for energy loss." },
    { id: 10, subject: "Covariant Formulation of the Poynting Vector", question: "Express the Poynting vector in covariant form using the electromagnetic field tensor and the four-velocity. Interpret energy flow and momentum density in a relativistic framework.", difficulty: "advanced", hint: "Use the four-dimensional formalism to express the Poynting vector and analyze the energy and momentum transfer in relativistic systems." },
    { id: 11, subject: "Electromagnetic Field of a Moving Dipole", question: "Derive the electric and magnetic fields for a moving dipole in special relativity. Explain how the dipole radiation pattern changes as the velocity approaches the speed of light.", difficulty: "challenging", hint: "Consider the relativistic effects of motion on the dipole field and use the Liénard-Wiechert potentials to find the resulting fields." },
    { id: 12, subject: "Magnetic Monopoles and Relativity", question: "Examine the theoretical concept of magnetic monopoles within the context of special relativity. How does the introduction of monopoles affect Maxwell’s equations?", difficulty: "advanced", hint: "Think about how the symmetry of Maxwell’s equations could be extended to include magnetic monopoles and what the implications are for the electromagnetic field tensor." },
    { id: 13, subject: "Unruh Effect and Electromagnetic Fields", question: "Explain the Unruh effect and discuss its relation to the behavior of electromagnetic fields in accelerated frames of reference.", difficulty: "advanced", hint: "Consider the analogy with the Hawking radiation for black holes and how accelerating observers perceive the vacuum." },
    { id: 14, subject: "Relativistic Maxwell–Boltzmann Distribution", question: "Derive the relativistic form of the Maxwell–Boltzmann distribution for particles in a plasma, and discuss its behavior in extreme conditions of velocity and temperature.", difficulty: "challenging", hint: "Use the relativistic energy-momentum relation to modify the classical Maxwell–Boltzmann distribution and analyze the effects of high velocities." },
    { id: 15, subject: "Magnetic Field Generation by Relativistic Charges", question: "Derive the magnetic field produced by a moving relativistic charge in special relativity. Discuss how the field differs from that of a static charge and how relativistic effects influence it.", difficulty: "intermediate", hint: "Use the Biot-Savart law in the relativistic framework and apply Lorentz transformations to determine the resulting field." }
]

,
 "thermodynamics-and-statistics": [
  { id: 1, subject: "First Law of Thermodynamics – Heat and Work", question: "A gas expands from volume V₁ to V₂ under a pressure that varies linearly with volume. Using the first law of thermodynamics, calculate the work done, change in internal energy, and heat exchanged if the gas is monoatomic.", difficulty: "intermediate", hint: "Use W = ∫P(V)dV and ΔU = (3/2)nRΔT for monoatomic gas." },
  { id: 2, subject: "Adiabatic vs Isothermal Expansion", question: "Compare the work done by an ideal gas during adiabatic and isothermal expansions from the same initial to final volume. Derive expressions for both and interpret the physical difference.", difficulty: "intermediate", hint: "Use PV^γ = const for adiabatic, and PV = nRT for isothermal." },
  { id: 3, subject: "Heat Engine – Carnot Cycle", question: "Sketch the Carnot cycle on a P-V diagram and derive the efficiency of a Carnot engine operating between two thermal reservoirs. Explain the physical significance of the result.", difficulty: "introductory", hint: "η = 1 - T_cold / T_hot for ideal reversible engines." },
  { id: 4, subject: "Entropy – Irreversible Process", question: "A metal block at temperature T₁ is placed in contact with a large thermal reservoir at temperature T₂. Calculate the total entropy change of the system and environment. Explain why entropy increases.", difficulty: "intermediate", hint: "Use ΔS = Q/T for each component and check signs." },
  { id: 5, subject: "Thermodynamic Potentials – Helmholtz Free Energy", question: "Starting from the first law and the definition of internal energy, derive the differential form of the Helmholtz free energy. Interpret the physical meaning in terms of equilibrium and stability.", difficulty: "advanced", hint: "F = U - TS, so dF = dU - TdS - SdT; use first law." },
  { id: 6, subject: "Heat Exchanger Efficiency", question: "Derive an expression for the efficiency of a counterflow heat exchanger given inlet and outlet temperatures. Explain how entropy generation is minimized in this configuration.", difficulty: "intermediate", hint: "Use ε = (T_hot,out - T_cold,in) / (T_hot,in - T_cold,in)." },
  { id: 7, subject: "Kinetic Theory of Gases – Pressure Derivation", question: "Using the kinetic theory of gases, derive the expression for pressure of an ideal monoatomic gas in terms of molecular speed. Explain the assumptions made in the derivation.", difficulty: "introductory", hint: "Start from force due to molecular collisions on walls." },
  { id: 8, subject: "Partition Function and Thermodynamic Quantities", question: "Given the single-particle partition function of a system, derive expressions for internal energy, entropy, and Helmholtz free energy. Apply this to a two-level quantum system.", difficulty: "challenging", hint: "U = -∂lnZ/∂β, S = -∂F/∂T, F = -kT lnZ." },
  { id: 9, subject: "Quantum Statistics – Bose-Einstein vs Fermi-Dirac", question: "Compare the distribution functions for Bose-Einstein and Fermi-Dirac statistics. Discuss physical systems where each applies and derive the expression for average occupation number.", difficulty: "advanced", hint: "Average n = 1 / (e^(ε−μ)/kT ± 1); plus for FD, minus for BE." },
  { id: 10, subject: "Second Law and Entropy Inequality", question: "State the Clausius inequality and use it to prove that entropy never decreases in an isolated system. Apply it to a closed cycle with irreversible processes.", difficulty: "intermediate", hint: "ΔS ≥ ∫δQ/T; equality holds for reversible processes only." },
  { id: 11, subject: "Maxwell Relations", question: "Derive the Maxwell relations from the thermodynamic potentials and show how they can be used to find changes in entropy or pressure.", difficulty: "advanced", hint: "Use the exact differentials of U, H, F, G and compare mixed partials." },
  { id: 12, subject: "Latent Heat and Phase Transitions", question: "Explain the concept of latent heat in first-order phase transitions. Derive the Clausius-Clapeyron equation for the coexistence curve.", difficulty: "intermediate", hint: "Use dP/dT = L / (TΔV) for phase equilibrium." },
  { id: 13, subject: "Equipartition Theorem", question: "State and apply the equipartition theorem to calculate the internal energy of monoatomic and diatomic gases at different temperatures.", difficulty: "introductory", hint: "Each quadratic degree of freedom contributes (1/2)kT to energy." },
  { id: 14, subject: "Thermodynamic Identity", question: "Derive the thermodynamic identity from the first law and explain its significance in terms of differentials of entropy, volume, and particle number.", difficulty: "intermediate", hint: "dU = TdS - PdV + μdN; comes from combining definitions." },
  { id: 15, subject: "Real Gases and van der Waals Equation", question: "Derive the van der Waals equation of state and compare it with the ideal gas law. Discuss physical interpretation of correction terms.", difficulty: "intermediate", hint: "Use (P + a/V²)(V - b) = nRT; explain a and b." },
  { id: 16, subject: "Heat Capacity Relations", question: "Derive the relation between Cp and Cv for an ideal gas and explain the physical meaning of the ratio γ = Cp/Cv.", difficulty: "introductory", hint: "Cp - Cv = nR for ideal gas; γ shows adiabatic behavior." },
  { id: 17, subject: "Third Law of Thermodynamics", question: "State the third law and explain how it constrains entropy at absolute zero. Discuss implications for cooling techniques.", difficulty: "intermediate", hint: "S → 0 as T → 0 for perfect crystals." },
  { id: 18, subject: "Boltzmann Distribution", question: "Derive the Boltzmann distribution from statistical arguments and explain its role in predicting populations in thermal equilibrium.", difficulty: "introductory", hint: "Use P(ε) ∝ e^(−ε/kT), normalize using partition function." }
 ],
 'quantum-mechanics': [
  { id: 1, subject: "Black Body Radiation and Quantization", question: "Explain how Planck's quantization hypothesis resolved the ultraviolet catastrophe in black body radiation. Derive the Planck radiation formula.", difficulty: "introductory", hint: "Assume energy is quantized: E = nhν; use this in deriving energy density." },
  { id: 2, subject: "Schrödinger Equation – 1D Infinite Well", question: "Solve the time-independent Schrödinger equation for a particle in a 1D infinite potential well. Find the quantized energy levels.", difficulty: "introductory", hint: "Boundary conditions lead to sin(nπx/L) solutions; Eₙ ∝ n²." },
  { id: 3, subject: "Quantum Tunneling – Potential Barrier", question: "For a particle facing a finite potential barrier, solve the Schrödinger equation and determine the transmission coefficient.", difficulty: "intermediate", hint: "Match wavefunctions and derivatives at boundaries; T ∝ e^(-2κa)." },
  { id: 4, subject: "Heisenberg Uncertainty Principle", question: "Using a Gaussian wave packet, derive the uncertainty relation between position and momentum and show minimal uncertainty.", difficulty: "intermediate", hint: "Use Δx·Δp ≥ ħ/2 and properties of Fourier transforms." },
  { id: 5, subject: "Free Particle – Momentum Wavefunction", question: "Find the momentum space wavefunction of a free particle. Interpret the result in terms of probability density.", difficulty: "intermediate", hint: "Fourier transform the position wavefunction to get ψ(p)." },
  { id: 6, subject: "Time Evolution of States", question: "Given a superposition of energy eigenstates, use the time-dependent Schrödinger equation to calculate the time-evolved wavefunction.", difficulty: "intermediate", hint: "Each term evolves with phase factor e^(−iEₙt/ħ)." },
  { id: 7, subject: "1D Harmonic Oscillator – Energy Quantization", question: "Solve the Schrödinger equation for the 1D quantum harmonic oscillator and derive the energy eigenvalues and eigenfunctions.", difficulty: "intermediate", hint: "Eₙ = (n + ½)ħω; solutions involve Hermite polynomials." },
  { id: 8, subject: "Spin-1/2 and Pauli Matrices", question: "Represent spin-1/2 states and spin operators using Pauli matrices. Calculate the expectation value of spin in a given state.", difficulty: "intermediate", hint: "Use ⟨ψ|σ|ψ⟩ for expectation; σₓ, σ_y, σ_z are Pauli matrices." },
  { id: 9, subject: "Angular Momentum – Commutation Relations", question: "Write and interpret the commutation relations between angular momentum operators. Define ladder operators and their action.", difficulty: "advanced", hint: "[Lₓ, L_y] = iħL_z; ladder operators raise/lower m values." },
  { id: 10, subject: "Dirac Formalism and Expectation Values", question: "Using Dirac notation, compute the expectation value of an operator in a known state. Apply to momentum and spin operators.", difficulty: "advanced", hint: "⟨ψ|A|ψ⟩ gives expectation value of operator A." },
  { id: 11, subject: "Quantum Measurement and State Collapse", question: "Describe the process of measurement in quantum mechanics. What happens to the wavefunction upon measurement of an observable?", difficulty: "introductory", hint: "Wavefunction collapses to an eigenstate of the measured observable." },
  { id: 12, subject: "Time-Independent Perturbation Theory", question: "Apply first-order perturbation theory to a quantum system with a small potential added to a known Hamiltonian.", difficulty: "challenging", hint: "First-order correction: Eₙ¹ = ⟨ψₙ⁰|H'|ψₙ⁰⟩." },
  { id: 13, subject: "Tunneling and Resonant States", question: "Discuss quantum tunneling in a double-barrier potential and explain the concept of resonant transmission.", difficulty: "challenging", hint: "At resonance, transmission is near 1 due to constructive interference." },
  { id: 14, subject: "3D Infinite Well – Degeneracy", question: "Solve the Schrödinger equation for a particle in a 3D infinite potential box and compute the degeneracies of energy levels.", difficulty: "intermediate", hint: "E ∝ nₓ² + n_y² + n_z²; degeneracy from permutations." },
  { id: 15, subject: "Quantum Operators and Eigenstates", question: "Define a quantum operator and derive the conditions under which a state is an eigenstate of an observable.", difficulty: "introductory", hint: "An eigenstate satisfies Â|ψ⟩ = a|ψ⟩, where a is the eigenvalue." }
]

,
  "relativity": [
  { id: 1, subject: "Lorentz Transformations", question: "Derive the Lorentz transformation equations from the postulates of special relativity. Show the invariance of the spacetime interval.", difficulty: "introductory", hint: "Start by considering the postulates of special relativity. The Lorentz transformations ensure the invariance of the spacetime interval (ds^2)."},
  { id: 2, subject: "Time Dilation", question: "Using Lorentz transformations, derive the formula for time dilation and apply it to a moving clock observed from a stationary frame.", difficulty: "introductory", hint: "Consider the time difference in the moving frame, and how it changes when viewed from the stationary frame using Lorentz factor (γ)."},
  { id: 3, subject: "Length Contraction", question: "Starting from Lorentz transformations, derive the expression for length contraction. Explain the result with a physical example.", difficulty: "introductory", hint: "Use the Lorentz transformation for spatial coordinates. Length contraction occurs along the direction of motion and is dependent on the relative velocity."},
  { id: 4, subject: "Relativity of Simultaneity", question: "Show how two events simultaneous in one inertial frame may not be simultaneous in another using Lorentz transformations.", difficulty: "introductory", hint: "Think about the concept of simultaneity and how it changes when viewed from a moving reference frame. The Lorentz transformations will demonstrate this."},
  { id: 5, subject: "Velocity Addition", question: "Derive the relativistic formula for addition of velocities. Apply it to a scenario involving two moving observers.", difficulty: "intermediate", hint: "Start with the classical addition of velocities and modify it to account for the speed of light limit using Lorentz transformations."},
  { id: 6, subject: "Invariant Interval", question: "Define the spacetime interval and demonstrate its invariance under Lorentz transformations. Classify intervals as timelike, spacelike, or lightlike.", difficulty: "intermediate", hint: "The spacetime interval is defined as ds^2 = c^2dt^2 - dx^2 - dy^2 - dz^2. Invariance means it remains the same in all inertial frames."},
  { id: 7, subject: "Twin Paradox", question: "Explain the twin paradox in special relativity and resolve the apparent contradiction using time dilation and acceleration.", difficulty: "intermediate", hint: "The resolution lies in the acceleration of the traveling twin, which breaks the symmetry between the two frames. Time dilation explains why the traveling twin ages slower."},
  { id: 8, subject: "Relativistic Doppler Effect", question: "Derive the formula for the relativistic Doppler shift for a source moving towards and away from the observer.", difficulty: "intermediate", hint: "Consider the relativistic velocity addition and incorporate the Lorentz factor to find the frequency shift in the observed signal."},
  { id: 9, subject: "Relativistic Energy and Momentum", question: "Define relativistic momentum and energy. Derive the energy-momentum relation and discuss its low-velocity limit.", difficulty: "intermediate", hint: "The energy-momentum relation is E^2 = (pc)^2 + (m₀c²)^2. In the low-velocity limit, this reduces to the classical expressions for energy and momentum."},
  { id: 10, subject: "Four-Vectors and Minkowski Space", question: "Introduce four-vectors in Minkowski space and show how the four-momentum transforms under Lorentz transformations.", difficulty: "intermediate", hint: "Four-vectors in Minkowski space represent events in spacetime. The four-momentum is a four-vector that transforms like other vectors under Lorentz transformations."},
  { id: 11, subject: "Equivalence Principle", question: "State the equivalence principle and describe its role in the formulation of general relativity. Give an example with free fall.", difficulty: "introductory", hint: "The equivalence principle states that locally (in small regions of spacetime), gravitational effects are indistinguishable from acceleration. This leads to the development of general relativity."},
  { id: 12, subject: "Curved Spacetime and Gravity", question: "Explain how gravity is described in general relativity as curvature of spacetime. Contrast this with Newtonian gravity.", difficulty: "introductory", hint: "In general relativity, gravity is not a force but the effect of curved spacetime. Mass tells spacetime how to curve, and curvature tells objects how to move."},
  { id: 13, subject: "Einstein Field Equations – Overview", question: "State the Einstein field equations and explain the physical meaning of each term. Discuss the role of the stress-energy tensor.", difficulty: "intermediate", hint: "The Einstein field equations are Gμν = 8πGTμν. Gμν is the Einstein tensor describing spacetime curvature, and Tμν is the stress-energy tensor, representing matter and energy."},
  { id: 14, subject: "Gravitational Time Dilation", question: "Use the Schwarzschild metric to derive the expression for gravitational time dilation near a massive body.", difficulty: "intermediate", hint: "The Schwarzschild metric describes spacetime outside a spherical, non-rotating mass. Time dilation occurs as the gravitational potential increases."},
  { id: 15, subject: "Light Deflection by Gravity", question: "Outline the derivation of the bending of light near a massive object using the principle of equivalence and curved spacetime.", difficulty: "intermediate", hint: "Use the equivalence principle to relate the deflection of light to the curvature of spacetime near a massive object. The bending angle can be derived from the metric around the mass."}
]

,
  "optics-and-waves": [
    { id: 1, subject: "Geometric Optics – Thin Lenses", question: "Using the lens maker's formula, derive the image position and magnification for a thin convex lens with a real object.", difficulty: "introductory", hint: "Recall the lens formula: 1/f = 1/v - 1/u and magnification = v/u." },
    { id: 2, subject: "Geometric Optics – Concave Mirror", question: "Analyze image formation by a concave mirror for an object placed beyond the center of curvature.", difficulty: "introductory", hint: "Use the mirror equation and sign convention: 1/f = 1/v + 1/u." },
    { id: 3, subject: "Ray Transfer Matrix – Optical Systems", question: "Use ABCD matrices to model a system of a lens and free space. Derive the system matrix and find the image location.", difficulty: "intermediate", hint: "Matrix multiplication order matters: free space → lens → free space." },
    { id: 4, subject: "Matrix Analysis – Stability of Optical Cavities", question: "Apply matrix formalism to determine the stability condition of a two-mirror resonator.", difficulty: "intermediate", hint: "Check the condition |(A + D)/2| < 1 for cavity stability." },
    { id: 5, subject: "Wave Optics – Double Slit Interference", question: "Derive the intensity pattern for a double-slit interference experiment and explain the fringe spacing.", difficulty: "introductory", hint: "Fringe spacing depends on wavelength and slit separation: Δy = λL/d." },
    { id: 6, subject: "Wave Optics – Single Slit Diffraction", question: "Calculate the angular position of minima in a single-slit diffraction pattern and interpret the physical significance.", difficulty: "introductory", hint: "Use a*sinθ = mλ for minima positions (m ≠ 0)." },
    { id: 7, subject: "Diffraction Grating – Wavelength Measurement", question: "Use a diffraction grating to derive the condition for constructive interference and determine the wavelength of light.", difficulty: "intermediate", hint: "Constructive interference: d*sinθ = mλ." },
    { id: 8, subject: "Thin Film Interference", question: "Analyze the conditions for constructive and destructive interference in a thin film with a given refractive index and thickness.", difficulty: "intermediate", hint: "Use 2nt = mλ for constructive and (2nt = (m + ½)λ) for destructive." },
    { id: 9, subject: "Quantum Optics – Photon Statistics", question: "Compare the photon number statistics for coherent, thermal, and Fock states of light.", difficulty: "advanced", hint: "Look at variance: coherent = Poissonian, thermal = super-Poissonian, Fock = sub-Poissonian." },
    { id: 10, subject: "Quantum Optics – Beam Splitter Transformation", question: "Write the quantum operator transformation for a beam splitter and analyze the resulting output states.", difficulty: "advanced", hint: "Use a linear transformation: a_out = r*a_in + t*b_in." },
    { id: 11, subject: "Fermat’s Principle and Lagrangian Optics", question: "Using the calculus of variations, derive the path of light in a medium with spatially varying refractive index.", difficulty: "advanced", hint: "Minimize the optical path length using Euler-Lagrange equations." },
    { id: 12, subject: "Optical Path Integral", question: "Outline Feynman's path integral approach to light propagation and compare it with classical ray optics.", difficulty: "advanced", hint: "Sum over all possible paths weighted by e^(iS/ħ), where S is the action." },
    { id: 13, subject: "Metamaterials – Negative Refractive Index", question: "Explain how metamaterials achieve a negative refractive index and analyze Snell's law for such materials.", difficulty: "advanced", hint: "Both permittivity and permeability are negative → negative index." },
    { id: 14, subject: "Metamaterials – Perfect Lens", question: "Discuss the theoretical basis for a perfect lens using a slab of negative index metamaterial and its resolution limits.", difficulty: "challenging", hint: "A perfect lens amplifies evanescent waves → subwavelength resolution." },
    { id: 15, subject: "Lagrangian Optics – Atmospheric Refraction", question: "Apply the variational principle to derive the bending of light in Earth's atmosphere with a graded refractive index.", difficulty: "advanced", hint: "Refractive index varies with height → curved light paths using Euler-Lagrange." }
  ]
,
  "solid-state-and-semiconductors": [
  { id: 1, subject: "Crystal Lattices and Unit Cells", question: "Define crystal lattice, basis, and unit cell. Distinguish between primitive and conventional cells with diagrams.", difficulty: "introductory", hint: "Think of a lattice as a periodic grid and the basis as the motif attached to each point. Diagrams help visualize the repetition." },
  { id: 2, subject: "2D and 3D Bravais Lattices", question: "List and describe the 2D and 3D Bravais lattices with examples of real crystal systems.", difficulty: "introductory", hint: "Start with 5 types in 2D and 14 types in 3D. Examples include cubic (NaCl), tetragonal (Sn), etc." },
  { id: 3, subject: "Crystal Structures – FCC, BCC, HCP", question: "Compare FCC, BCC, and HCP structures in terms of atomic packing factor, coordination number, and examples.", difficulty: "introductory", hint: "FCC has highest packing efficiency (74%), BCC is ~68%, HCP also 74% but non-cubic." },
  { id: 4, subject: "Miller Indices", question: "Determine the Miller indices of a plane in a cubic lattice and compute the angle between two planes.", difficulty: "intermediate", hint: "Use intercepts → reciprocals → clearing fractions. For angle, use dot product formula with direction vectors." },
  { id: 5, subject: "Bragg’s Law and Diffraction", question: "Apply Bragg’s law to calculate the diffraction angle and lattice spacing in an X-ray experiment.", difficulty: "intermediate", hint: "nλ = 2d sinθ is your key equation. Start with known λ and θ to find d." },
  { id: 6, subject: "Reciprocal Lattice – Construction", question: "Construct the reciprocal lattice for a 2D square and hexagonal lattice, and explain its physical meaning.", difficulty: "intermediate", hint: "Reciprocal lattice vectors are derived from cross products of direct lattice vectors." },
  { id: 7, subject: "First Brillouin Zone", question: "Define and construct the first Brillouin zone for a 2D square lattice and discuss its significance.", difficulty: "intermediate", hint: "It’s the Wigner-Seitz cell in reciprocal space, central to electronic band theory." },
  { id: 8, subject: "Drude Model – Electrical Conductivity", question: "Derive the expression for conductivity using the Drude model and discuss its limitations.", difficulty: "introductory", hint: "Use classical free-electron gas model, Ohm’s law, and τ (relaxation time)." },
  { id: 9, subject: "Sommerfeld Model – Quantum Free Electrons", question: "Explain how the Sommerfeld model improves on the Drude model and calculate the Fermi energy.", difficulty: "intermediate", hint: "It incorporates Fermi-Dirac statistics and quantum energy levels instead of classical ones." },
  { id: 10, subject: "Density of States in 1D, 2D, 3D", question: "Derive the density of states function for a free electron gas in 1D, 2D, and 3D.", difficulty: "intermediate", hint: "Use k-space volume and energy-momentum relation to find DOS ∝ √E (in 3D)." },
  { id: 11, subject: "Fermi Level and Fermi Surface", question: "Explain the concept of the Fermi level and calculate the number of occupied states at T = 0 K.", difficulty: "intermediate", hint: "At T = 0 K, all states below the Fermi level are filled. Use the density of states and energy integration." },
  { id: 12, subject: "Bloch’s Theorem", question: "State and prove Bloch’s theorem for electrons in a periodic potential.", difficulty: "advanced", hint: "Bloch's theorem states that wavefunctions in a periodic potential can be written as a plane wave modulated by a function with the periodicity of the lattice." },
  { id: 13, subject: "Kronig–Penney Model", question: "Solve the Kronig–Penney model to derive the energy band structure of a 1D crystal.", difficulty: "challenging", hint: "Use the potential well function and solve the Schrödinger equation to obtain energy bands and band gaps." },
  { id: 14, subject: "Band Gaps and Electronic Properties", question: "Distinguish between metals, semiconductors, and insulators using band theory.", difficulty: "introductory", hint: "Metals have overlapping conduction and valence bands, semiconductors have a small gap, and insulators have a large gap." },
  { id: 15, subject: "Effective Mass of Electrons", question: "Define effective mass and derive it from the curvature of the E–k relation near the band edge.", difficulty: "intermediate", hint: "Effective mass is the inverse of the second derivative of the energy vs. wavevector relation." },
  { id: 16, subject: "Intrinsic and Extrinsic Semiconductors", question: "Compare intrinsic and extrinsic semiconductors and calculate carrier concentrations at a given temperature.", difficulty: "intermediate", hint: "Intrinsic semiconductors have equal electron and hole concentrations, while extrinsic ones depend on doping type and level." },
  { id: 17, subject: "Doping and Fermi Level Shift", question: "Analyze how doping with donors or acceptors shifts the Fermi level in a semiconductor.", difficulty: "intermediate", hint: "Doping adds carriers that shift the Fermi level toward the conduction band (donors) or the valence band (acceptors)." },
  { id: 18, subject: "PN Junction – Formation and Behavior", question: "Explain the formation of the depletion region in a PN junction and analyze current-voltage characteristics.", difficulty: "intermediate", hint: "The depletion region forms due to diffusion of carriers, and the I-V curve follows a diode-like exponential behavior." },
  { id: 19, subject: "Zener and Avalanche Breakdown", question: "Compare Zener and avalanche breakdown mechanisms and their dependence on doping and temperature.", difficulty: "intermediate", hint: "Zener breakdown occurs due to high field ionization, while avalanche breakdown is due to impact ionization, both sensitive to doping levels." },
  { id: 20, subject: "Photodiodes and LEDs", question: "Explain the operation of a photodiode and LED, and describe how band structure determines emitted light wavelength.", difficulty: "intermediate", hint: "Photodiodes work by generating current under illumination, while LEDs emit light due to electron-hole recombination at a junction." },
  { id: 21, subject: "Bipolar Junction Transistor (BJT)", question: "Describe the structure and operation of an NPN transistor in active mode, with energy band diagrams.", difficulty: "intermediate", hint: "BJTs have three layers: emitter, base, and collector, and operate based on current injection and amplification." },
  { id: 22, subject: "MOSFET Structure and Operation", question: "Explain how a MOSFET operates in enhancement and depletion modes using energy bands and gate voltage control.", difficulty: "intermediate", hint: "MOSFETs control current flow via an electric field created by a gate voltage, with enhancement mode allowing conduction and depletion mode inhibiting it." },
  { id: 23, subject: "JFET and FET Types", question: "Compare JFET and MOSFET characteristics, including pinch-off, threshold voltage, and current saturation.", difficulty: "intermediate", hint: "JFETs control current through a reverse-biased p-n junction, while MOSFETs use an insulated gate to control current." },
  { id: 24, subject: "CMOS Inverter – Logic and Power", question: "Describe how a CMOS inverter works and explain its low power consumption in digital logic.", difficulty: "intermediate", hint: "CMOS inverters use complementary p-channel and n-channel MOSFETs, switching states with minimal power dissipation." },
  { id: 25, subject: "Semiconductor Fabrication – Lithography", question: "List and explain steps in CMOS fabrication, focusing on photolithography, doping, and etching.", difficulty: "intermediate", hint: "Lithography is used for patterning, doping adds impurities, and etching removes material to create features in the semiconductor." }
]

,

}


// -------------------------RENDERING PROBLEMS SECTION ----------------------------------------------
// now make the api available
app.get( `/courses/:topicId/problems` , (req,res)=>{
    let { topicId } = req.params; // dynamically unfolds the arary of dynamics elements
    
    console.log(`Running request get on : ${topicId}`);
    
    // if i have dynamic elements i ll make like { param1 , param2 , param3 } = req.params; => that is destructuring the object
    const topicProblems = availableProblemsBasedOnTopics[ topicId ];
    if( topicProblems ){
        res.json( { success: true , problems: topicProblems } );
    }else{
        res.status(404).json({ success: false , message: "Topic not found or not available" });
    }
} );


// ------------------------------------------------------------------------------------------------
// SOURCING THE REGISTRATION AND LOGIN MICROSERVICES HERE
const loginRoute = require('./server_routes/login');
const registerRoute = require( './server_routes/register' );
app.use( '/login' , loginRoute );
app.use( '/register' , registerRoute );



//----------TRACKING LOGIC FOR COURSES------------------------------------------------
const visitedCoursesRoute = require( './server_routes/visited-courses' );
app.use('/visited-courses' , visitedCoursesRoute );



// APP LISTENING HERE -----------------------------------------------
// starting my server
app.listen( PORT, () => {
    console.log(`Server is running on http://localhost:${PORT}`);
  });